# Generated by Django 5.2.5 on 2025-08-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('accessories', 'Accessories')], max_length=20)),
                ('image', models.ImageField(upload_to='merchandise/')),
                ('has_sizes', models.BooleanField(default=False)),
            ],
        ),
    ]
