# Generated by Django 5.2.5 on 2025-08-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='created_at',
            new_name='date_subscribed',
        ),
    ]
